# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QGridLayout


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(120, 98, 561, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.messages = QtWidgets.QTextBrowser(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(120, 170, 561, 241))
        self.messages.setObjectName("messages")
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(120, 480, 561, 41))
        self.text.setObjectName("text")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(700, 490, 75, 23))
        self.btn_send.setObjectName("btn_send")
        self.btn_code = QtWidgets.QPushButton(self.centralwidget)
        self.btn_code.setGeometry(QtCore.QRect(700, 390, 75, 23))
        self.btn_code.setObjectName("btn_code")
        self.btn_code_strim = QtWidgets.QPushButton(self.centralwidget)
        self.btn_code_strim.setGeometry(QtCore.QRect(700, 290, 75, 23))
        self.btn_code_strim.setObjectName("btn_code_strim")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(700, 190, 75, 23))
        self.btn_del.setObjectName("btn_del")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Messanger"))
        # self.name.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.text.setPlaceholderText(_translate("MainWindow", "Введите сообщение"))
        self.btn_send.setText(_translate("MainWindow", "Отправить"))
        self.btn_code.setText(_translate("Mainwindow", "Code"))
        self.btn_code_strim.setText(_translate('Mainwindow', 'Strim'))
        self.btn_del.setText(_translate('Mainwindow', 'Delete'))

