# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 270)
        Form.setMinimumSize(QtCore.QSize(410, 270))
        Form.setMaximumSize(QtCore.QSize(410, 270))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.registration_btn = QtWidgets.QPushButton(Form)
        self.registration_btn.setGeometry(QtCore.QRect(230, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.registration_btn.setFont(font)
        self.registration_btn.setObjectName("registration_btn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(140, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 60, 311, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_name_text = QtWidgets.QLabel(self.widget)
        self.user_name_text.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_name_text.setFont(font)
        self.user_name_text.setObjectName("user_name_text")
        self.horizontalLayout.addWidget(self.user_name_text)
        self.registration_name = QtWidgets.QLineEdit(self.widget)
        self.registration_name.setObjectName("registration_name")
        self.horizontalLayout.addWidget(self.registration_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_login_text = QtWidgets.QLabel(self.widget)
        self.user_login_text.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_login_text.setFont(font)
        self.user_login_text.setObjectName("user_login_text")
        self.horizontalLayout_2.addWidget(self.user_login_text)
        self.registration_login = QtWidgets.QLineEdit(self.widget)
        self.registration_login.setObjectName("registration_login")
        self.horizontalLayout_2.addWidget(self.registration_login)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_password_text = QtWidgets.QLabel(self.widget)
        self.user_password_text.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_password_text.setFont(font)
        self.user_password_text.setObjectName("user_password_text")
        self.horizontalLayout_3.addWidget(self.user_password_text)
        self.registration_password = QtWidgets.QLineEdit(self.widget)
        self.registration_password.setObjectName("registration_password")
        self.horizontalLayout_3.addWidget(self.registration_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.registration_btn.setText(_translate("Form", "Зарегистрироваться"))
        self.label_4.setText(_translate("Form", "Регистрация"))
        self.user_name_text.setText(_translate("Form", "Имя:"))
        self.user_login_text.setText(_translate("Form", "Логин:"))
        self.user_password_text.setText(_translate("Form", "Пароль:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Registration()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
