# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 270)
        Form.setMinimumSize(QtCore.QSize(410, 270))
        Form.setMaximumSize(QtCore.QSize(410, 270))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 301, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enter_login_text = QtWidgets.QLabel(self.layoutWidget)
        self.enter_login_text.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_login_text.setFont(font)
        self.enter_login_text.setObjectName("enter_login_text")
        self.horizontalLayout_2.addWidget(self.enter_login_text)
        self.enter_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_login.setObjectName("enter_login")
        self.horizontalLayout_2.addWidget(self.enter_login)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.enter_password_text = QtWidgets.QLabel(self.layoutWidget)
        self.enter_password_text.setMinimumSize(QtCore.QSize(65, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_password_text.setFont(font)
        self.enter_password_text.setObjectName("enter_password_text")
        self.horizontalLayout_3.addWidget(self.enter_password_text)
        self.enter_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_password.setObjectName("enter_password")
        self.horizontalLayout_3.addWidget(self.enter_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.enter_btn = QtWidgets.QPushButton(Form)
        self.enter_btn.setGeometry(QtCore.QRect(220, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_btn.setFont(font)
        self.enter_btn.setObjectName("enter_btn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.enter_registration_btn = QtWidgets.QPushButton(Form)
        self.enter_registration_btn.setGeometry(QtCore.QRect(10, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_registration_btn.setFont(font)
        self.enter_registration_btn.setObjectName("enter_registration_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enter_login_text.setText(_translate("Form", "Логин:"))
        self.enter_password_text.setText(_translate("Form", "Пароль:"))
        self.enter_btn.setText(_translate("Form", "Войти"))
        self.label_4.setText(_translate("Form", "Вход"))
        self.enter_registration_btn.setText(_translate("Form", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Enter()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
